/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IIconoirCloudSync: typeof import('~icons/iconoir/cloud-sync')['default']
    IIconoirDownload: typeof import('~icons/iconoir/download')['default']
    IIconoirHalfMoon: typeof import('~icons/iconoir/half-moon')['default']
    IIconoirMinus: typeof import('~icons/iconoir/minus')['default']
    IIconoirPauseSolid: typeof import('~icons/iconoir/pause-solid')['default']
    IIconoirPlaySolid: typeof import('~icons/iconoir/play-solid')['default']
    IIconoirPlus: typeof import('~icons/iconoir/plus')['default']
    IIconoirSoundOff: typeof import('~icons/iconoir/sound-off')['default']
    IIconoirSunLight: typeof import('~icons/iconoir/sun-light')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadio: typeof import('naive-ui')['NRadio']
    Presence: typeof import('./src/components/Sync.vue')['default']
    QR: typeof import('./src/components/QR.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sync: typeof import('./src/components/Sync.vue')['default']
    TimePicker: typeof import('./src/components/TimePicker.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    VoicePicker: typeof import('./src/components/VoicePicker.vue')['default']
  }
}
